// This file has been autogenerated
// Some parts may have been validated and configured manually

export interface Event {
    id: string;
    type: string;
    actor: Actor;
    repo: Repo;
    payload: Payload;
    public: boolean;
    created_at: string;
}
export interface Actor {
    id: number;
    login: string;
    display_login: string;
    gravatar_id: string;
    url: string;
    avatar_url: string;
}
export interface Repo {
    id: number;
    name: string;
    url: string;
}
export interface Payload {
    action?: string | null;
    number?: number | null;
    pull_request?: PullRequest | null;
    ref?: string | null;
    ref_type?: string | null;
    master_branch?: string | null;
    description?: string | null;
    pusher_type?: string | null;
    push_id?: number | null;
    size?: number | null;
    distinct_size?: number | null;
    head?: string | null;
    before?: string | null;
    commits?: (CommitsEntity)[] | null;
    issue?: Issue | null;
}
export interface PullRequest {
    url: string;
    id: number;
    node_id: string;
    html_url: string;
    diff_url: string;
    patch_url: string;
    issue_url: string;
    number: number;
    state: string;
    locked: boolean;
    title: string;
    user: OwnerOrUser;
    body: string;
    created_at: string;
    updated_at: string;
    closed_at?: null;
    merged_at?: null;
    merge_commit_sha?: null;
    assignee?: null;
    assignees?: (null)[] | null;
    requested_reviewers?: (null)[] | null;
    requested_teams?: (null)[] | null;
    labels?: (null)[] | null;
    milestone?: null;
    commits_url: string;
    review_comments_url: string;
    review_comment_url: string;
    comments_url: string;
    statuses_url: string;
    head: HeadOrBase;
    base: HeadOrBase;
    _links: Links;
    author_association: string;
    merged: boolean;
    mergeable?: null;
    rebaseable?: null;
    mergeable_state: string;
    merged_by?: null;
    comments: number;
    review_comments: number;
    maintainer_can_modify: boolean;
    commits: number;
    additions: number;
    deletions: number;
    changed_files: number;
}
export interface OwnerOrUser {
    login: string;
    id: number;
    node_id: string;
    avatar_url: string;
    gravatar_id: string;
    url: string;
    html_url: string;
    followers_url: string;
    following_url: string;
    gists_url: string;
    starred_url: string;
    subscriptions_url: string;
    organizations_url: string;
    repos_url: string;
    events_url: string;
    received_events_url: string;
    type: string;
    site_admin: boolean;
}
export interface HeadOrBase {
    label: string;
    ref: string;
    sha: string;
    user: OwnerOrUser;
    repo: Repo1;
}
export interface Repo1 {
    id: number;
    node_id: string;
    name: string;
    full_name: string;
    private: boolean;
    owner: OwnerOrUser;
    html_url: string;
    description: string;
    fork: boolean;
    url: string;
    forks_url: string;
    keys_url: string;
    collaborators_url: string;
    teams_url: string;
    hooks_url: string;
    issue_events_url: string;
    events_url: string;
    assignees_url: string;
    branches_url: string;
    tags_url: string;
    blobs_url: string;
    git_tags_url: string;
    git_refs_url: string;
    trees_url: string;
    statuses_url: string;
    languages_url: string;
    stargazers_url: string;
    contributors_url: string;
    subscribers_url: string;
    subscription_url: string;
    commits_url: string;
    git_commits_url: string;
    comments_url: string;
    issue_comment_url: string;
    contents_url: string;
    compare_url: string;
    merges_url: string;
    archive_url: string;
    downloads_url: string;
    issues_url: string;
    pulls_url: string;
    milestones_url: string;
    notifications_url: string;
    labels_url: string;
    releases_url: string;
    deployments_url: string;
    created_at: string;
    updated_at: string;
    pushed_at: string;
    git_url: string;
    ssh_url: string;
    clone_url: string;
    svn_url: string;
    homepage?: null;
    size: number;
    stargazers_count: number;
    watchers_count: number;
    language?: null;
    has_issues: boolean;
    has_projects: boolean;
    has_downloads: boolean;
    has_wiki: boolean;
    has_pages: boolean;
    forks_count: number;
    mirror_url?: null;
    archived: boolean;
    disabled: boolean;
    open_issues_count: number;
    license: License;
    forks: number;
    open_issues: number;
    watchers: number;
    default_branch: string;
}
export interface License {
    key: string;
    name: string;
    spdx_id: string;
    url: string;
    node_id: string;
}
export interface Links {
    self: SelfOrHtmlOrIssueOrCommentsOrReviewCommentsOrReviewCommentOrCommitsOrStatuses;
    html: SelfOrHtmlOrIssueOrCommentsOrReviewCommentsOrReviewCommentOrCommitsOrStatuses;
    issue: SelfOrHtmlOrIssueOrCommentsOrReviewCommentsOrReviewCommentOrCommitsOrStatuses;
    comments: SelfOrHtmlOrIssueOrCommentsOrReviewCommentsOrReviewCommentOrCommitsOrStatuses;
    review_comments: SelfOrHtmlOrIssueOrCommentsOrReviewCommentsOrReviewCommentOrCommitsOrStatuses;
    review_comment: SelfOrHtmlOrIssueOrCommentsOrReviewCommentsOrReviewCommentOrCommitsOrStatuses;
    commits: SelfOrHtmlOrIssueOrCommentsOrReviewCommentsOrReviewCommentOrCommitsOrStatuses;
    statuses: SelfOrHtmlOrIssueOrCommentsOrReviewCommentsOrReviewCommentOrCommitsOrStatuses;
}
export interface SelfOrHtmlOrIssueOrCommentsOrReviewCommentsOrReviewCommentOrCommitsOrStatuses {
    href: string;
}
export interface CommitsEntity {
    sha: string;
    author: Author;
    message: string;
    distinct: boolean;
    url: string;
}
export interface Author {
    email: string;
    name: string;
}
export interface Issue {
    url: string;
    repository_url: string;
    labels_url: string;
    comments_url: string;
    events_url: string;
    html_url: string;
    id: number;
    node_id: string;
    number: number;
    title: string;
    user: OwnerOrUser;
    labels?: (null)[] | null;
    state: string;
    locked: boolean;
    assignee?: null;
    assignees?: (null)[] | null;
    milestone?: null;
    comments: number;
    created_at: string;
    updated_at: string;
    closed_at?: null;
    author_association: string;
    body: string;
}
