// This file has been autogenerated

// Webhook Schema

export interface Webhook {
    action: Action;
    model: Model;
}
export interface Action {
    id: string;
    idMemberCreator: string;
    data: Data;
    type: string;
    date: string;
    memberCreator: MemberCreator;
}
export interface Data {
    board: Board;
    card: Card;
    voted: boolean;
}
export interface Board {
    name: string;
    id: string;
}
export interface Card {
    idShort: number;
    name: string;
    id: string;
}
export interface MemberCreator {
    id: string;
    avatarHash: string;
    fullName: string;
    initials: string;
    username: string;
}
export interface Model {
    id: string;
    name: string;
    desc: string;
    closed: boolean;
    idOrganization: string;
    pinned: boolean;
    url: string;
    prefs: Prefs;
    labelNames: LabelNames;
}
export interface Prefs {
    permissionLevel: string;
    voting: string;
    comments: string;
    invitations: string;
    selfJoin: boolean;
    cardCovers: boolean;
    canBePublic: boolean;
    canBeOrg: boolean;
    canBePrivate: boolean;
    canInvite: boolean;
}
export interface LabelNames {
    yellow: string;
    red: string;
    purple: string;
    orange: string;
    green: string;
    blue: string;
}

// Member Schema

export interface Member {
    id: string;
    activityBlocked: boolean;
    avatarHash: string;
    avatarUrl: string;
    bio: string;
    bioData?: null;
    confirmed: boolean;
    fullName: string;
    idEnterprise: string;
    idEnterprisesDeactivated?: (null)[] | null;
    idMemberReferrer?: null;
    idPremOrgsAdmin?: (null)[] | null;
    initials: string;
    memberType: string;
    nonPublic?: boolean;
    nonPublicAvailable: boolean;
    products?: (number)[] | null;
    url: string;
    username: string;
    status: string;
    aaEmail: string;
    aaId: string;
    avatarSource: string;
    email: string;
    gravatarHash: string;
    idBoards?: (string)[] | null;
    idOrganizations?: (string)[] | null;
    idEnterprisesAdmin?: (null)[] | null;
    limits: Limits;
    loginTypes?: (string)[] | null;
    marketingOptIn: MarketingOptIn;
    messagesDismissed?: (MessagesDismissedEntity)[] | null;
    oneTimeMessagesDismissed?: (string)[] | null;
    prefs: Prefs;
    trophies?: (null)[] | null;
    uploadedAvatarHash: string;
    uploadedAvatarUrl: string;
    premiumFeatures?: (string)[] | null;
    isAaMastered: boolean;
    ixUpdate: string;
    idBoardsPinned?: null;
}
export interface Limits {
    boards: BoardsOrOrgs;
    orgs: BoardsOrOrgs;
}
export interface BoardsOrOrgs {
    totalPerMember: TotalPerMember;
}
export interface TotalPerMember {
    status: string;
    disableAt: number;
    warnAt: number;
}
export interface MarketingOptIn {
    optedIn: boolean;
    date: string;
}
export interface MessagesDismissedEntity {
    name: string;
    count: number;
    lastDismissed: string;
    _id: string;
}
export interface Prefs {
    privacy: Privacy;
    sendSummaries: boolean;
    minutesBetweenSummaries: number;
    minutesBeforeDeadlineToNotify: number;
    colorBlind: boolean;
    locale: string;
}
export interface Privacy {
    fullName: string;
    avatar: string;
}
