// This file has been autogenerated

export interface Schema {
    action: Action;
    model: Model;
}

export interface Action {
    id: string;
    idMemberCreator: string;
    data: Data;
    type: string;
    date: string;
    memberCreator: MemberCreator;
}

export interface Data {
    board: Board;
    card: Card;
    voted: boolean;
}

export interface Board {
    name: string;
    id: string;
}

export interface Card {
    idShort: number;
    name: string;
    id: string;
}

export interface MemberCreator {
    id: string;
    avatarHash: string;
    fullName: string;
    initials: string;
    username: string;
}

export interface Model {
    id: string;
    name: string;
    desc: string;
    closed: boolean;
    idOrganization: string;
    pinned: boolean;
    url: string;
    prefs: Prefs;
    labelNames: LabelNames;
}

export interface Prefs {
    permissionLevel: string;
    voting: string;
    comments: string;
    invitations: string;
    selfJoin: boolean;
    cardCovers: boolean;
    canBePublic: boolean;
    canBeOrg: boolean;
    canBePrivate: boolean;
    canInvite: boolean;
}

export interface LabelNames {
    yellow: string;
    red: string;
    purple: string;
    orange: string;
    green: string;
    blue: string;
}
